name: Deploy website on dev tag

on:
  push:
    tags:
      - '*dev*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:  Use Node.js
        uses: actions/setup-node@v1
        with:
          fetch-depth: 0
          always-auth: true
          node-version: '14.2.0'
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Echo version
        run: echo ${{ steps.get_version.outputs.VERSION }}
